language: go

go:
  - 1.8
  - 1.9

os:
  - linux

before_install:
  - test -z $(gofmt -l .)
  - go get github.com/golang/lint/golint
  - golint -set_exit_status .
  - go vet ./...
  - go get -t -v ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
